### ISSUE TITLE
Minor typo (I assume) in README.md

### ISSUE THREAD

**Issue by GregDThomas** [djBo/stomp4j#2]
Your README.md has a typo (I assume):

> Example code for making a connection:
> 
>    URL url = new URL("http://myhost.org:61613/");

Surely that URL should be:

```
URL url = new URL("stomp://myhost.org:61613/");
```

**Comment by djBo** [comment]
Updated :)
Thanks!

**Comment by GregDThomas** [comment]
PS. Another one;

> Connections are made using the following url:
> 
> stomp://[<username>:<password>]@hostname[:port]/>

That last line should be:
     stomp://[<username>:<password>@]hostname[:port]/>
(i.e. the "@" should be inside the brackets indicating optionality)

**Comment by djBo** [comment]
Updated :)
Thanks!
